### ISSUE TITLE
vim integration

### ISSUE THREAD

**Issue by omares** [AuditeMarlow/base16-manager#18]
Hey, can you verify that the vim integration is working?

Looking at the code i see that [the manager sets the appropriate `colorscheme`](https://github.com/AuditeMarlow/base16-manager/blob/master/base16-manager#L307) but i do not understand how vim can find the themes as they are not stored in the `.vim/colors` directory?

**Comment by gardart** [comment]
when I run
$ base16-manager set monokai

The vimrc_background file doesnt look right, its missing the theme

cat .vimrc_background

if !exists('g:colors_name') || g:colors_name != 'base16-'
  colorscheme base16-
endif

**Comment by gardart** [comment]
I fixed it by adding this to my vimrc and now it works

if filereadable(expand("~/.vim/colorscheme.vim"))
    let base16colorspace=256
    source ~/.vim/colorscheme.vim
else
    colorscheme desert
endif

**Comment by omares** [comment]
@gardart does theming vim using the base16-manager work for you? How did you install base16-vim, using the manager or by hand?

**Comment by gardart** [comment]
it was already installed but I did also install it with the manager.
Yes it work inside vim after I changed my vimrc to use colorscheme.vim file

**Comment by AuditeMarlow** [comment]
Meh. The way base16-vim is integrated is probably the silliest thing ever. I can't assume all colors are available in `~/.vim/colors`, since plugin managers often don't store color plugins directly in there. Also, NeoVim stores its configuration files elsewhere completely.

Now, as for base16-manager's Vim support... I'm mainly relying on having already imported `chriskempson/base16-vim` with my plugin manager. using `base16-manager set materia`, I simply write to a `colorscheme.vim` file that is supposed to be included in your vimrc. I agree this is not the best way to support base16-vim, but honestly, I have no clue how to properly support this, and do not have enough time or motivation to come up with a better solution to this problem.

This leaves us pretty much at the start. I suggest if you want to use base16 colors with vim, you import Chris Kempson's base16-vim plugin with your plugin manager, set a theme with `base16-manager set <theme>` and add `source /path/to/colorscheme.vim` to your vimrc.

**Comment by RageKnify** [comment]
> add source /path/to/colorscheme.vim to your vimrc.

I had the same problem and doing this seems to fix it, but you should probably mention this somewhere @AuditeMarlow .

**Comment by AuditeMarlow** [comment]
I've updated the readme that mentions the colorscheme.vim stuff [here](here). That ought to be enough for now.

**Comment by thiagodebastos** [comment]
> I've updated the readme that mentions the colorscheme.vim stuff [here](here). That ought to be enough for now.

FYI that link is now broken.
