### ISSUE TITLE
List installed themes

### ISSUE THREAD

**Issue by chrokh** [AuditeMarlow/base16-manager#4]
`base16-manager list` lists installed templates.

Is listing installed themes on the roadmap?

I am not familiar enough with the `base16` tool chain to understand where we should source the list of themes from.

But if someone could allude to an implementation I can take a stab at a first PR.

**Comment by AuditeMarlow** [comment]
Listing themes is a good one, actually. Listing themes is kind of tricky, because there is no defined list of base16 themes. In fact, Chris Kempson's [base16 repository](https://github.com/chriskempson/base16) motivates people to create their own base16 themes.

What we could do, is to check what themes are installed per template, and list the unique ones.

**Comment by chrokh** [comment]
Simple implementation suggestion in #6 . Not well versed in bash so please feel free to comment on style.

**Comment by AuditeMarlow** [comment]
Resolved as of 037eefe.
